In [1]:
import tensorflow as tf


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[407, 2379, 736, 8909],
 [407, 2379, 736, 7364],
 [407, 9941, 736, 7829],
 [3969, 9893, 5865, 4311, 5515],
 [3969, 9893, 5865, 4311, 2501],
 [1172, 407, 5877, 736, 651],
 [8676, 4182, 7555, 4311]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  407 2379  736 8909]
 [   0    0    0    0  407 2379  736 7364]
 [   0    0    0    0  407 9941  736 7829]
 [   0    0    0 3969 9893 5865 4311 5515]
 [   0    0    0 3969 9893 5865 4311 2501]
 [   0    0    0 1172  407 5877  736  651]
 [   0    0    0    0 8676 4182 7555 4311]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 328ms/step


array([[[-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
         -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
          2.9835377e-02, -2.3883903e-02],
        [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
         -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
          2.9835377e-02, -2.3883903e-02],
        [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
         -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
          2.9835377e-02, -2.3883903e-02],
        [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
         -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
          2.9835377e-02, -2.3883903e-02],
        [-1.2247302e-02,  2.4582390e-02,  3.9470065e-02,  2.1994207e-02,
          4.8906319e-03, -4.6979010e-02, -4.0440448e-03,  3.9472710e-02,
         -3.1485811e-02, -4.6817876e-02],
        [ 2.5169600e-02, -4.7854256e-02,  2.6861753e-02,  3.

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0,  407, 2379,  736, 8909])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 151ms/step


array([[-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
        -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
         2.9835377e-02, -2.3883903e-02],
       [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
        -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
         2.9835377e-02, -2.3883903e-02],
       [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
        -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
         2.9835377e-02, -2.3883903e-02],
       [-1.1160113e-02,  3.6089566e-02, -7.9750642e-03, -9.2969425e-03,
        -2.7400065e-02, -4.2182602e-02, -1.6107976e-02,  1.2406480e-02,
         2.9835377e-02, -2.3883903e-02],
       [-1.2247302e-02,  2.4582390e-02,  3.9470065e-02,  2.1994207e-02,
         4.8906319e-03, -4.6979010e-02, -4.0440448e-03,  3.9472710e-02,
        -3.1485811e-02, -4.6817876e-02],
       [ 2.5169600e-02, -4.7854256e-02,  2.6861753e-02,  3.2486860e-02,
   